fix action

diff --git a/.github/workflows/pull-request-enforce-checklist.yml b/.github/workflows/pull-request-enforce-checklist.yml
--- a/.github/workflows/pull-request-enforce-checklist.yml
+++ b/.github/workflows/pull-request-enforce-checklist.yml
@@ -4,6 +4,11 @@ on:
   pull_request:
     types: [opened, edited, synchronize]
 
+env:
+  changelog_checkbox: "This PR doesn't need to update changelog"
+  unit_test_checkbox: "I have either added unit tests for this feature or confirmed it doesn't need unit tests"
+  environment_checkbox: "I have tested this feature in an environment (e.g., production, development, local)"
+
 jobs:
   validate-pr:
     runs-on: ubuntu-latest
@@ -13,40 +18,48 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Validate PR checklist
+        env:
+          BODY: ${{ github.event.pull_request.body }}
         id: checklist
         run: |
-          # Load PR description into a variable
-          pr_body=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
+          UNCHECKED_CHANGELOG="\[ \] $changelog_checkbox"
+          MARKED_CHANGELOG="\[x\] $changelog_checkbox"
+          
+          UNCHECKED_TEST="\[ \] $unit_test_checkbox"
+          MARKED_TEST="\[x\] $unit_test_checkbox"
+          
+          UNCHECKED_ENV="\[ \] $environment_checkbox"
+          MARKED_ENV="\[x\] $environment_checkbox"
 
-          # Define required checkboxes in both checked and unchecked forms
-          changelog_checkbox_checked="- [x] This PR doesn't need to update changelog"
-          changelog_checkbox_unchecked="- [ ] This PR doesn't need to update changelog"
-          unit_test_checkbox_checked="- [x] I have either added unit tests for this feature or confirmed it doesn't need unit tests"
-          unit_test_checkbox_unchecked="- [ ] I have either added unit tests for this feature or confirmed it doesn't need unit tests"
-          environment_checkbox_checked="- [x] I have tested this feature in an environment (e.g., production, development, local)"
-          environment_checkbox_unchecked="- [ ] I have tested this feature in an environment (e.g., production, development, local)"
-
-          # Function to check for checkboxes
-          check_checkbox() {
-            # Use printf to output and grep for required strings
-            if ! printf "%s\n" "$pr_body" | grep -Fxq "$1" && ! printf "%s\n" "$pr_body" | grep -Fxq "$2"; then
-              echo "::error::$3"
-              exit 1
-            fi
-          }
-
-          # Check each required checkbox
-          check_checkbox "$changelog_checkbox_checked" "$changelog_checkbox_unchecked" \
-            "Please check the box to indicate if this PR doesn't need to update changelog."
-
-          check_checkbox "$unit_test_checkbox_checked" "$unit_test_checkbox_unchecked" \
-            "Please check the box to confirm if unit tests were added or if they're not needed."
-
-          check_checkbox "$environment_checkbox_checked" "$environment_checkbox_unchecked" \
-            "Please check the box to confirm the feature was tested in an environment."
-
-          # Changelog update verification if the checkbox is unchecked
-          if printf "%s\n" "$pr_body" | grep -Fxq "$changelog_checkbox_unchecked" && ! git diff --name-only origin/main | grep -q "changelog.md"; then
-            echo "::error::Changelog entry required. Please add a change in changelog.md or check the box."
+          # Check the Changelog checkbox
+          if echo "${BODY,,}" | grep -q "$MARKED_CHANGELOG"; then
+            echo "Changelog Checkbox is checked"
+          elif echo "${BODY,,}" | grep -q "$UNCHECKED_CHANGELOG"; then
+            echo "Changelog Checkbox is not checked"
+            exit 1
+          else
+            echo "Changelog Checkbox not found in pull request description"
+            exit 1
+          fi
+          
+          # Check the Unit Test checkbox
+          if echo "${BODY,,}" | grep -q "$MARKED_TEST"; then
+            echo "Unit Test Checkbox is checked"
+          elif echo "${BODY,,}" | grep -q "$UNCHECKED_TEST"; then
+            echo "Unit Test Checkbox is not checked"
+            exit 1
+          else
+            echo "Unit Test Checkbox not found in pull request description"
+            exit 1
+          fi
+          
+          # Check the Environment checkbox
+          if echo "${BODY,,}" | grep -q "$MARKED_ENV"; then
+            echo "Environment Checkbox is checked"
+          elif echo "${BODY,,}" | grep -q "$UNCHECKED_ENV"; then
+            echo "Environment Checkbox is not checked"
+            exit 1
+          else
+            echo "Environment Checkbox not found in pull request description"
             exit 1
           fi
